version: '3.1'

services:
    db:
        image: mysql:latest
        container_name: db-mysql
        restart: always

        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql
        env_file:
            - ./mysql/db-config.env

    mqtt:
        image: eclipse-mosquitto:latest
        container_name: mqtt
        ports:
            - '1883:1883'
        volumes:
            - ./mosquitto:/mosquitto

        
volumes:
    mysql-data:
